### PR TITLE
Merges updates from upstream/main to tf012

### PR DESCRIPTION
**Pull request by lorengordon**

### CODE REVIEW

**Comment by kbalk** [comment]
There are "build" failures in the terraform-related code that Plus3IT were involved in.  Are you planning to correct them or should I?

There are over 2000 files modified in this merge.  There is a smaller portion of those changed files that could impact the terraform-related files, but it'll take a bit of work to figure that out.  It might make sense to do a merge on a more frequent basis so it's more manageable.

**Comment by lorengordon** [comment]
I wasn't really expecting the CI to run at all, since this is a fork and usually any CI can only ever succeed when running on the upstream project. What tests are you looking at, exactly, that you're expecting to succeed (links preferred)?

**Comment by kbalk** [comment]
https://github.com/plus3it/dependabot-core/pull/44/checks?check_run_id=2395258962

It appears they've bolstered `rubocop`; they've updated the version of `rubocop` and its config file to find more errors, which it has.

**Comment by kbalk** [comment]
I think the `Gemfile.lock` file would also need updating.

**Comment by kbalk** [comment]
Also `Dockerfile.ci` was changed and there are now packager-dependent `xxx/script/ci-test`.  Although as I get further through the changes, perhaps that's been modified further.

https://github.com/plus3it/dependabot-core/pull/44/commits/0877a99e035694a01a20adad62814f978e2107b5

**Comment by lorengordon** [comment]
The only changes we need to worry about here are those to files that we modified. We don't need to review the entirety of the changeset, as the dependabot team has done their own review. Also, I've already exercised this branch in our implementations to confirm it does work, but I will at least update our changes to make the linter happy and correct the tests we added.

**Comment by kbalk** [comment]
I'm not reviewing their changes for correctness, I'm reviewing them to see what changes impact our contributions:

- They've made changes to the common libraries and I'm not sure that will impact us, although the unit tests should give us a clue.
- They've made significant changes to their CI/CD files, including their Docker files.  As I said, they've moved some of the CI tests to individual files rather than lump them all in one larger file.  I would expect merge issues.

Besides improving their common libraries and CI/CD process, they've made improvement for python, go and azure.

I've only gotten up to the changes made on April 20.

**Comment by lorengordon** [comment]
@kbalk The terraform CI test is now passing. There are a few new upstream commits because I pulled in the latest upstream tag... There was some external dependency that was causing a CI failure, that the dependabot team had updated since the CI last ran on this PR. I'm also re-running a dry-run on our private implementation, using this branch as the source.

**Comment by lorengordon** [comment]
The private implementation is still running fine on the current HEAD of this branch, 2ab99ba.

**Comment by kbalk** [comment]
There are changes to `terraform/spec/dependabot/terraform/update_checker_spec.rb` and `terraform/spec/dependabot/terraform/requirement_spec.rb` that we do not have.  I haven't studied them to see if we should have those changes:  They are in this commit (scroll down to the very bottom):

https://github.com/dependabot/dependabot-core/commit/21560ff706a58336fcb8d2ba375bf216b1f698bb#diff-94dc3ea57721d541aae09b7bf2368c1e20d4c89996ff6df4349d86048877c0e7

I found it was easier to go to the dependabot-core github, then down to the terraform directory and look at the commits there.  Although it's nice to get a sense of what's been changing overall.

**Comment by lorengordon** [comment]
Those changes are included in this pull request, as of merging the upstream tag v0.143.4 this morning.

**Comment by kbalk** [comment]
Ok.  As part of a review, I should also re-run dry-run, but I think I'm going to pass if that's ok.  Otherwise, I'm ready to approve.

**Comment by kbalk** [comment]
And it's ok that the github, python and common CI/CI tests fail?

**Comment by lorengordon** [comment]
It's ok to me. We haven't done anything to affect those parsers, so I think they either must be flaky tests or depending on secrets we don't have access to in a fork.

**Review by kbalk — APPROVED** [review]

**Review by kbalk — APPROVED** [review]

**Review by kbalk — APPROVED** [review]
Looks good

**Pull request merged**
